### PR TITLE
Add gitignore and change role checks

### PR DESCRIPTION
**Pull request by Hikari-Haru**
Annoying not having one

### CODE REVIEW

**Comment by Kav-K** [comment]
Totally forgot ;)

**Review by Kav-K — DISMISSED** [review]

**Comment by Hikari-Haru** [comment]
Whoops

**Comment by Hikari-Haru** [comment]
Made some further convenience changes for how the roles are checked, doing it as part of the slash_command decorator. Should make it easier to add other checks too and remove them from the function itself

**Comment by Kav-K** [comment]
This looks great, I'll test it locally after CI and merge. Thank you for the contribution!

**Comment by Hikari-Haru** [comment]
Hey, no problem, I'm working on private threads and probably also the preamble. A little busy with the new years so I haven't had the time to do a pull request yet

**Comment by Kav-K** [comment]
> Hey, no problem, I'm working on private threads and probably also the preamble. A little busy with the new years so I haven't had the time to do a pull request yet

No worries at all and please take your time, I very much appreciate the help! I've dismissed my review for this for a moment because I want some quick info from you (I commented above) but I think after that this is good to merge

**Comment by Hikari-Haru** [comment]
> No worries at all and please take your time, I very much appreciate the help! I've dismissed my review for this for a moment because I want some quick info from you (I commented above) but I think after that this is good to merge

I'm not sure if I'm blind but I can't see the comment you're referring to. Only seen the comment where you mentioned testing locally 😅

**Comment by Kav-K** [comment]
> > No worries at all and please take your time, I very much appreciate the help! I've dismissed my review for this for a moment because I want some quick info from you (I commented above) but I think after that this is good to merge
> 
> I'm not sure if I'm blind but I can't see the comment you're referring to. Only seen the comment where you mentioned testing locally 😅

Oh that's so weird, here are screenshots
image


image

**Comment by Hikari-Haru** [comment]
> Oh that's so weird, here are screenshots
> image
> 
> 
> image
> 

Might be a mobile GitHub thing, the error I'll have to check at home. The parameters worked, but I haven't checked it since removing the openai token. Should still work though as it's not a big change

**Comment by Hikari-Haru** [comment]
I've ran it again and the settings parameter list works for me on both pc and mobile on the up to date commit .
For vscode I have "Python" and "Pylance" installed with the type checking disabled in the lower right corner.
Either way, I changed the function to use respond instead, since respond just calls followup anyways

**Review by Kav-K — APPROVED** [review]

**Comment by Kav-K** [comment]
Looks good to me. Merging shortly @Hikari-Haru

**Pull request merged**
